### ISSUE TITLE
How to force regeneration of interlanguage links?

### ISSUE THREAD

**Issue by roland2025** [SemanticMediaWiki/SemanticInterlanguageLinks#30]
Hi.

The combination "en":"Main Page" already exsits for page "SomePage" therefore no additional interlanguage annotation was created.

But 'SomePage' already has interlanguage link to 'AnotherPage'.

Managed to get to this situation, after creating a template
with the contents of {{INTERLANGUAGELINK: en | {{PAGENAME}} }}
and adding that template to 'AnotherPage'

Regards, 
Roland

**Comment by roland2025** [comment]
If you'd like to take a look, https://www.ubuntu.ee

**Comment by mwjames** [comment]
> The combination "en":"Main Page" already exsits for page "SomePage" therefore no additional interlanguage annotation was created.

This happens because it defines the same "parent" with the same language key and we want to avoid that content is referring to content with the same "parent" and with the "same" language more than once. We had a discussion about this #8 and I couldn't find any plausible use case that would make "Multiple reference pointer" likely to produce a satisfactory output.

> Managed to get to this situation, after creating a template

When you create an annotation (with help of `{{INTERLANGUAGELINK: en | {{PAGENAME}} }}` it will create two statements about the page that embeds the annotation. For example, a page Foo with `{{INTERLANGUAGELINK: en | Bar }}` would have statements about:
- Foo -> has page content language of -> en
- Foo -> is referring to a "super" page of -> Bar

The so called "super" page could be also the original content page Foo but that can be arbitrarily (or better by free association) decided as long as each page that represents the same content is referring to the same "super" page.

Links are collected for a "super" page to make sure that a tree like structure can be build:
Bar
 |- en -> Foo
 |- fr -> F...

Normally your template should define the "parent" instead of using {{PAGENAME}} so that it is clear what a page the content is referring to (`ContentDescription` is a wrapper for `{{INTERLANGUAGELINK: ...}}`).

`Page One` contains
```
{{ContentDescription
 |language=en
 |isabout=Page about something
}}
```

`ページ一` contains
```
{{ContentDescription
 |language=ja
 |isabout=Page about something
}}
```

Page three (error)
```
{{ContentDescription
 |language=en
 |isabout=Page about something
}}
```
If the third page wants to use (`en:Page about something`) again it would produce an error because it tries to represent content for an already existing (`en:Page about something`) and that would create two "en" links and "mean" to point to the same content for the same language (which one is the correct one?). 

> If you'd like to take a look, https://www.ubuntu.ee

I hope that the above explanation helps a bit, otherwise let me know which page exactly is causing you trouble.

**Comment by mwjames** [comment]
@kghbln Maybe our smw.org content guru has some insights?

**Comment by roland2025** [comment]
I just wanted to try, if this template would work, I don't really need it at the moment.

Would just want to fix the Main Page article :)

**Comment by roland2025** [comment]
It seems, that running runJobs.php and refreshLinks.php a couple of times, fixed the problem.

Thanks
