### ISSUE TITLE
SIL and MobileFrontend combination not working

### ISSUE THREAD

**Issue by roland2025** [SemanticMediaWiki/SemanticInterlanguageLinks#31]
Is this a problem with SIL or MobileFrontend?

**Comment by mwjames** [comment]
> Is this a problem with SIL or MobileFrontend?

I don't use (or better not really know MobileFrontend) therefore I can't say what "not working" means. Do you refer to the interlanguage links?

**Comment by roland2025** [comment]
You can take a look,  
1. go to https://www.ubuntu.ee/wiki
2. scroll to the end and press "mobile view"
3. scroll to the end: there is a button "read in another langugage", press it
4. problem is visible
5. the links that show up redirect to Sil:en:Main_Page

**Comment by mwjames** [comment]
Well, I'm guessing this has to do with the hooks they use to create the list. The one we use the extend the list is [0].

[0] https://www.mediawiki.org/wiki/Manual:Hooks/SkinTemplateGetLanguageLink

**Comment by mwjames** [comment]
After quick (really quick) look at [0] it doesn't seem that MobileFrontend BaseTemplate calls [1] but SkinMinerva [2] does but whether it executes the hook or not I can't say.

I can't debug this because I have no time to install MobileFrontend. The best thing would be for you (if you know how PHP works) the set a break point/`var_dump` in the above mentioned hook and see whether MobileFrontend passes the hook or not.

[0] https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FMobileFrontend/3d5d996d1b8dcff4f4304366033cc5d5679ad71b/includes%2Fskins%2FMinervaTemplate.php#L90

[1] https://doc.wikimedia.org/mediawiki-core/master/php/SkinTemplate_8php_source.html#l00071

[2] https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FMobileFrontend/3d5d996d1b8dcff4f4304366033cc5d5679ad71b/includes%2Fskins%2FSkinMinerva.php#L439

**Comment by kghbln** [comment]
MobileFrontend is now installed on sandbox. The "Read in another language" button indeed does not appear but now you get [scrambled chars on the top right](http://sandbox.semantic-mediawiki.org/w/index.php?title=Mainz&mobileaction=toggle_view_mobile) linking to "Special:MobileLanguages" which does not find other languages.

**Comment by mwjames** [comment]
> The "Read in another language" button indeed does not appear but now you get scrambled chars on the top right

I've seen that and it's because `MobileFrontend` does handle those links differently than the desktop. I don't remember whether something could be done or not (its a while that I had a look at it).

**Comment by mwjames** [comment]
Closing as of "... it's because MobileFrontend does handle those links ...".

**Comment by kghbln** [comment]
The future has MinervaNeue in place for us. I think it is save to guess that it will not be able to handle this either.
